export const CitiesWeather: object = [
  {
    name: 'Cairo',
    springN: 18,
    springM: 30,
    summerN: 28,
    summerM: 43,
    winterN: 12,
    winterM: 25,
    autumnN: 22,
    autumnM: 36,
    visitFrom: 'October',
    visitTo: 'April',
  },
  {
    name: 'Aswan',
    springN: 18,
    springM: 30,
    summerN: 28,
    summerM: 43,
    winterN: 12,
    winterM: 25,
    autumnN: 22,
    autumnM: 36,
    visitFrom: 'October',
    visitTo: 'April',
  },
  {
    name: 'Hurghada',
    springN: 18,
    springM: 30,
    summerN: 28,
    summerM: 43,
    winterN: 12,
    winterM: 25,
    autumnN: 22,
    autumnM: 36,
    visitFrom: 'October',
    visitTo: 'April',
  },
];
